#!/bin/bash
#Check if start-sway_machine_specific_config exists and source it
[[ -f ./start-sway_machine_specific_config ]] && source ./start-sway_machine_specific_config

# ---------- Xwayland ------------
# ensure xdg run dir exists and is clean
[[ -d "/tmp/run/$USER" ]] && rm -rf "/tmp/run/$USER"
mkdir -p "/tmp/run/$USER"
chmod 0700 "/tmp/run/$USER"
XDG_RUNTIME_DIR="/tmp/run/$USER"

#setup other variables
mkdir -p "$HOME"/.{config,cache,local/share}
XDG_DATA_HOME="$HOME/.local/share"
XDG_DATA_DIRS="/usr/local/share:/usr/share"
XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"

export XDG_RUNTIME_DIR XDG_DATA_{HOME,DIRS} XDG_{CONFIG,CACHE}_HOME

QT_QPA_PLATFORM=qt5ct
MOZ_ENABLE_WAYLAND=1
GDK_BACKEND=wayland
CLUTTER_BACKEND=wayland
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=sway

export QT_QPA_PLATFORM MOZ_ENABLE_WAYLAND GDK_BACKEND CLUTTER_BACKEND XDG_SESSION_TYPE XDG_SESSION_DESKTOP

sway 
