
[font]
size = 12.0

[font.bold]
family = "Hasklug Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hasklug Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hasklug Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
dynamic_title = true
dynamic_padding = true
opacity = 0.95

[general]
import = ["/home/ddxtanx/.config/alacritty/themes/themes/tokyo-night.toml"]
